---
- name: run handler and restart services
  meta: flush_handlers

- name: check if the services are running
  systemd:
    name: "{{ item }}"
    state: started
  with_items:
    - haproxy
    - gunicorn
    - mariadb
    - tcpdump

- name: test if /api/v1/network works
  uri:
    url: "http://{{ ansible_default_ipv4.address }}/api/v1/network"
  register: api_output

- name: print API status
  assert:
    that: '"LISTEN" in "{{ api_output }}"'
    fail_msg: "API is not working :("
    success_msg: "API is working :)"

- name: show ip of vulnbox
  debug:
    msg: "IP of the vulnbox is {{ ansible_all_ipv4_addresses }}"
